logging:
  level:
    org:
      springframework: "WARN"
      apache:
        catalina: "WARN"
        directory: "WARN"

server:
  port: 8090

lookup:
  recursive:
    enabled: true
    allowedCidr:
      - '127.0.0.0/8'
      - '10.0.0.0/8'
      - '172.16.0.0/12'
      - '192.168.0.0/16'
      - '::1/128'

    bridge:
      enabled: false
      recursiveOnly: true

rest:
  endpoints:
    auth: "/_mxisd/identity/api/v1/auth"
    identity:
      single: "/_mxisd/identity/api/v1/lookup/single"
      bulk: "/_mxisd/identity/api/v1/lookup/bulk"

ldap:
  enabled: false
  connection:
    tls: false
    port: 389
  attribute:
    uid:
      type: 'uid'
      value: 'userPrincipalName'
    name: 'displayName'
  identity:
    medium:
      email: "(|(mailPrimaryAddress=%3pid)(mail=%3pid)(otherMailbox=%3pid))"
      msisdn: "(|(telephoneNumber=+%3pid)(mobile=+%3pid)(homePhone=+%3pid)(otherTelephone=+%3pid)(otherMobile=+%3pid)(otherHomePhone=+%3pid))"

firebase:
  enabled: false

sql:
  type: 'sqlite'

forward:
  servers:
    - "https://matrix.org"
    - "https://vector.im"

invite:
  sender:
    email:
      tls: 1
      name: "mxisd Identity Server"
      template: "classpath:email/invite-template.eml"

storage:
  backend: 'sqlite'
